################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
WiFly_Commands.obj: ../Source/App/WiFly_Commands.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.2/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -Ooff --opt_for_speed=2 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.2/include" --include_path="C:/ti/controlSUITE/development_kits/TIDM-SERVO-LAUNCHXS/MonoMtrServo_377s_v1_00_00_00/utility Src Files" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v170/F2837xS_headers/include" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v170/F2837xS_common/include" --include_path="C:/ti/controlSUITE/libs/app_libs/motor_control/math_blocks/v4.3" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_headers/include" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/TI/Drivers" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_common/include/FlashAPI" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_common/include" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_common" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v160/include" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/TI/HAL" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/motors" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/motors/HAL" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/Source/Header" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v160/include" --advice:performance=all -g --define="_DEBUG" --define=_FLASH --define="CPU1" --define="LARGE_MODEL" --quiet --diag_warning=225 -k --asm_listing --preproc_with_compile --preproc_dependency="Source/App/WiFly_Commands.pp" --tmu_support=tmu0 $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

config_mode_cmd.obj: ../Source/App/config_mode_cmd.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.2/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -Ooff --opt_for_speed=2 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.2/include" --include_path="C:/ti/controlSUITE/development_kits/TIDM-SERVO-LAUNCHXS/MonoMtrServo_377s_v1_00_00_00/utility Src Files" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v170/F2837xS_headers/include" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v170/F2837xS_common/include" --include_path="C:/ti/controlSUITE/libs/app_libs/motor_control/math_blocks/v4.3" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_headers/include" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/TI/Drivers" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_common/include/FlashAPI" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_common/include" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_common" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v160/include" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/TI/HAL" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/motors" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/motors/HAL" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/Source/Header" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v160/include" --advice:performance=all -g --define="_DEBUG" --define=_FLASH --define="CPU1" --define="LARGE_MODEL" --quiet --diag_warning=225 -k --asm_listing --preproc_with_compile --preproc_dependency="Source/App/config_mode_cmd.pp" --tmu_support=tmu0 $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

flash.obj: ../Source/App/flash.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.2/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -Ooff --opt_for_speed=2 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.2/include" --include_path="C:/ti/controlSUITE/development_kits/TIDM-SERVO-LAUNCHXS/MonoMtrServo_377s_v1_00_00_00/utility Src Files" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v170/F2837xS_headers/include" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v170/F2837xS_common/include" --include_path="C:/ti/controlSUITE/libs/app_libs/motor_control/math_blocks/v4.3" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_headers/include" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/TI/Drivers" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_common/include/FlashAPI" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_common/include" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_common" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v160/include" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/TI/HAL" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/motors" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/motors/HAL" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/Source/Header" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v160/include" --advice:performance=all -g --define="_DEBUG" --define=_FLASH --define="CPU1" --define="LARGE_MODEL" --quiet --diag_warning=225 -k --asm_listing --preproc_with_compile --preproc_dependency="Source/App/flash.pp" --tmu_support=tmu0 $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

fsm_main.obj: ../Source/App/fsm_main.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.2/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -Ooff --opt_for_speed=2 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.2/include" --include_path="C:/ti/controlSUITE/development_kits/TIDM-SERVO-LAUNCHXS/MonoMtrServo_377s_v1_00_00_00/utility Src Files" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v170/F2837xS_headers/include" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v170/F2837xS_common/include" --include_path="C:/ti/controlSUITE/libs/app_libs/motor_control/math_blocks/v4.3" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_headers/include" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/TI/Drivers" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_common/include/FlashAPI" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_common/include" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_common" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v160/include" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/TI/HAL" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/motors" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/motors/HAL" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/Source/Header" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v160/include" --advice:performance=all -g --define="_DEBUG" --define=_FLASH --define="CPU1" --define="LARGE_MODEL" --quiet --diag_warning=225 -k --asm_listing --preproc_with_compile --preproc_dependency="Source/App/fsm_main.pp" --tmu_support=tmu0 $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

hal_button.obj: ../Source/App/hal_button.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.2/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -Ooff --opt_for_speed=2 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.2/include" --include_path="C:/ti/controlSUITE/development_kits/TIDM-SERVO-LAUNCHXS/MonoMtrServo_377s_v1_00_00_00/utility Src Files" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v170/F2837xS_headers/include" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v170/F2837xS_common/include" --include_path="C:/ti/controlSUITE/libs/app_libs/motor_control/math_blocks/v4.3" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_headers/include" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/TI/Drivers" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_common/include/FlashAPI" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_common/include" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_common" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v160/include" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/TI/HAL" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/motors" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/motors/HAL" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/Source/Header" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v160/include" --advice:performance=all -g --define="_DEBUG" --define=_FLASH --define="CPU1" --define="LARGE_MODEL" --quiet --diag_warning=225 -k --asm_listing --preproc_with_compile --preproc_dependency="Source/App/hal_button.pp" --tmu_support=tmu0 $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

hal_led.obj: ../Source/App/hal_led.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.2/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -Ooff --opt_for_speed=2 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.2/include" --include_path="C:/ti/controlSUITE/development_kits/TIDM-SERVO-LAUNCHXS/MonoMtrServo_377s_v1_00_00_00/utility Src Files" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v170/F2837xS_headers/include" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v170/F2837xS_common/include" --include_path="C:/ti/controlSUITE/libs/app_libs/motor_control/math_blocks/v4.3" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_headers/include" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/TI/Drivers" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_common/include/FlashAPI" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_common/include" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_common" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v160/include" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/TI/HAL" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/motors" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/motors/HAL" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/Source/Header" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v160/include" --advice:performance=all -g --define="_DEBUG" --define=_FLASH --define="CPU1" --define="LARGE_MODEL" --quiet --diag_warning=225 -k --asm_listing --preproc_with_compile --preproc_dependency="Source/App/hal_led.pp" --tmu_support=tmu0 $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

led_intern.obj: ../Source/App/led_intern.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.2/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -Ooff --opt_for_speed=2 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.2/include" --include_path="C:/ti/controlSUITE/development_kits/TIDM-SERVO-LAUNCHXS/MonoMtrServo_377s_v1_00_00_00/utility Src Files" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v170/F2837xS_headers/include" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v170/F2837xS_common/include" --include_path="C:/ti/controlSUITE/libs/app_libs/motor_control/math_blocks/v4.3" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_headers/include" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/TI/Drivers" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_common/include/FlashAPI" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_common/include" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_common" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v160/include" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/TI/HAL" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/motors" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/motors/HAL" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/Source/Header" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v160/include" --advice:performance=all -g --define="_DEBUG" --define=_FLASH --define="CPU1" --define="LARGE_MODEL" --quiet --diag_warning=225 -k --asm_listing --preproc_with_compile --preproc_dependency="Source/App/led_intern.pp" --tmu_support=tmu0 $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

pwm_servo.obj: ../Source/App/pwm_servo.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.2/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -Ooff --opt_for_speed=2 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.2/include" --include_path="C:/ti/controlSUITE/development_kits/TIDM-SERVO-LAUNCHXS/MonoMtrServo_377s_v1_00_00_00/utility Src Files" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v170/F2837xS_headers/include" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v170/F2837xS_common/include" --include_path="C:/ti/controlSUITE/libs/app_libs/motor_control/math_blocks/v4.3" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_headers/include" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/TI/Drivers" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_common/include/FlashAPI" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_common/include" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_common" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v160/include" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/TI/HAL" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/motors" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/motors/HAL" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/Source/Header" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v160/include" --advice:performance=all -g --define="_DEBUG" --define=_FLASH --define="CPU1" --define="LARGE_MODEL" --quiet --diag_warning=225 -k --asm_listing --preproc_with_compile --preproc_dependency="Source/App/pwm_servo.pp" --tmu_support=tmu0 $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

steering_config.obj: ../Source/App/steering_config.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.2/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -Ooff --opt_for_speed=2 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.2/include" --include_path="C:/ti/controlSUITE/development_kits/TIDM-SERVO-LAUNCHXS/MonoMtrServo_377s_v1_00_00_00/utility Src Files" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v170/F2837xS_headers/include" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v170/F2837xS_common/include" --include_path="C:/ti/controlSUITE/libs/app_libs/motor_control/math_blocks/v4.3" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_headers/include" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/TI/Drivers" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_common/include/FlashAPI" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_common/include" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_common" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v160/include" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/TI/HAL" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/motors" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/motors/HAL" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/Source/Header" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v160/include" --advice:performance=all -g --define="_DEBUG" --define=_FLASH --define="CPU1" --define="LARGE_MODEL" --quiet --diag_warning=225 -k --asm_listing --preproc_with_compile --preproc_dependency="Source/App/steering_config.pp" --tmu_support=tmu0 $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

steering_control.obj: ../Source/App/steering_control.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.2/bin/cl2000" -v28 -ml -mt --cla_support=cla0 --float_support=fpu32 --tmu_support=tmu0 --vcu_support=vcu2 -Ooff --opt_for_speed=2 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-c2000_6.4.2/include" --include_path="C:/ti/controlSUITE/development_kits/TIDM-SERVO-LAUNCHXS/MonoMtrServo_377s_v1_00_00_00/utility Src Files" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v170/F2837xS_headers/include" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v170/F2837xS_common/include" --include_path="C:/ti/controlSUITE/libs/app_libs/motor_control/math_blocks/v4.3" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_headers/include" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/TI/Drivers" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_common/include/FlashAPI" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_common/include" --include_path="C:/ti/controlSUITE/device_support/F2837xS/v191/F2837xS_common" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v160/include" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/TI/HAL" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/motors" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/motors/HAL" --include_path="U:/02_MSE/MT/07_Software/CCS_workspace/DiffDrive_v0.93/Source/Header" --include_path="C:/ti/controlSUITE/libs/math/IQmath/v160/include" --advice:performance=all -g --define="_DEBUG" --define=_FLASH --define="CPU1" --define="LARGE_MODEL" --quiet --diag_warning=225 -k --asm_listing --preproc_with_compile --preproc_dependency="Source/App/steering_control.pp" --tmu_support=tmu0 $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


